// ============================================================
//  BATCH 4 — Skullcandy, Motorola, Multilaser, Philco,
//             JLab, Jaybird, Tozo, Ugreen, Tronsmart
//  Modelos ativos no Brasil — Abril 2026
//  Cole antes do ]; no headphones.js
// ============================================================

// ── SKULLCANDY ────────────────────────────────────────────────────────────────
{id:400,name:"Skullcandy Crusher ANC 2",brand:"Skullcandy",price:799,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.2","Autonomia":"50h","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"290g","Codec":"SBC, AAC"},pros:["Graves sensoriais ajustáveis — recurso único","50h de autonomia","ANC incluído","Design vibrante","Fio removível"],cons:["Sem LDAC","Graves sensoriais geram vibração incômoda para alguns","Build plástico"],score:{"Som":78,"Conforto":76,"Autonomia":90,"Custo-Benefício":76,"Build":68},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","Bass Test"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Crusher+ANC+2",ml:"https://lista.mercadolivre.com.br/skullcandy-crusher-anc-2",official:"https://skullcandy.com.br"},
{id:401,name:"Skullcandy Crusher Evo",brand:"Skullcandy",price:499,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"40h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"275g","Codec":"SBC, AAC"},pros:["Graves sensoriais ajustáveis — exclusivo da marca","40h de autonomia","Design marcante","Fio removível","Preço acessível"],cons:["Sem ANC","Sem LDAC","BT 5.0","Graves sensoriais dividem opiniões"],score:{"Som":74,"Conforto":74,"Autonomia":88,"Custo-Benefício":78,"Build":66},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","Bass Test"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Crusher+Evo",ml:"https://lista.mercadolivre.com.br/skullcandy-crusher-evo",official:"https://skullcandy.com.br"},
{id:402,name:"Skullcandy Hesh ANC",brand:"Skullcandy",price:399,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"22h ANC","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"231g","Codec":"SBC, AAC"},pros:["ANC por preço acessível","Leve 231g","Dobrável","Design discreto","Modo ambiente"],cons:["Sem LDAC","22h com ANC — abaixo da concorrência","BT 5.0"],score:{"Som":72,"Conforto":78,"Autonomia":72,"Custo-Benefício":76,"Build":64},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Hesh+ANC",ml:"https://lista.mercadolivre.com.br/skullcandy-hesh-anc",official:"https://skullcandy.com.br"},
{id:403,name:"Skullcandy Hesh Evo",brand:"Skullcandy",price:299,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"36h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"220g","Codec":"SBC, AAC"},pros:["36h de autonomia","Leve 220g","Dobrável","Preço acessível","Fio removível"],cons:["Sem ANC","Sem LDAC","BT 5.0","Qualidade intermediária"],score:{"Som":70,"Conforto":74,"Autonomia":85,"Custo-Benefício":78,"Build":62},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Hesh+Evo",ml:"https://lista.mercadolivre.com.br/skullcandy-hesh-evo",official:"https://skullcandy.com.br"},
{id:404,name:"Skullcandy Push Active",brand:"Skullcandy",price:299,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.2","Autonomia":"6h+28h case","Recarga":"2h","ANC":"Não","Microfone":"Sim","IPX":"IP55","Peso":"6g/fone","Codec":"SBC, AAC"},pros:["IP55","34h total","Design esportivo","Ganchos de orelha seguros","BT 5.2"],cons:["Sem ANC","Sem LDAC","Qualidade sonora básica"],score:{"Som":64,"Conforto":70,"Autonomia":80,"Custo-Benefício":74,"Build":68},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Push+Active",ml:"https://lista.mercadolivre.com.br/skullcandy-push-active",official:"https://skullcandy.com.br"},
{id:405,name:"Skullcandy Grind ANC",brand:"Skullcandy",price:349,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.2","Autonomia":"10h+30h case","Recarga":"2h","ANC":"Sim","Microfone":"Sim","IPX":"IPX4","Peso":"5.5g/fone","Codec":"SBC, AAC"},pros:["10h por carga — excelente","ANC incluído","40h total","IPX4","Carga 10min=2h"],cons:["Sem LDAC","ANC básico","IPX4 apenas"],score:{"Som":68,"Conforto":72,"Autonomia":88,"Custo-Benefício":76,"Build":64},youtubeIds:["XNRWh-fkDpk","OA_1pkrBx5g"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Skullcandy+Grind+ANC",ml:"https://lista.mercadolivre.com.br/skullcandy-grind-anc",official:"https://skullcandy.com.br"},

// ── MOTOROLA ──────────────────────────────────────────────────────────────────
{id:410,name:"Motorola Moto Buds+",brand:"Motorola",price:799,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"12mm","Bluetooth":"5.3","Autonomia":"7h+30h case","Recarga":"1.5h (wireless)","ANC":"Sim (46dB Bose-tuned)","Microfone":"3 mics","IPX":"IP54","Peso":"5.5g/fone","Codec":"SBC, AAC, LDAC"},pros:["Som sintonizado pela Bose","ANC 46dB forte","LDAC","IP54","Wireless charging no case","37h total"],cons:["App Motorola menos polido","Preço acima de similares","Autonomia reduz com ANC"],score:{"Som":82,"Conforto":78,"Autonomia":80,"Custo-Benefício":76,"Build":76},youtubeIds:["NMWYt5n4eZY","bH7_Qz3zVkk"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Motorola+Moto+Buds+Plus",ml:"https://lista.mercadolivre.com.br/motorola-moto-buds-plus",official:"https://www.motorola.com.br"},
{id:411,name:"Motorola Moto Buds 500",brand:"Motorola",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm","Bluetooth":"5.3","Autonomia":"6h+12h case","Recarga":"1h","ANC":"Sim (40dB)","Microfone":"3 mics","IPX":"IP54","Peso":"5.2g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC 40dB","LDAC","IP54","18h total","Design elegante"],cons:["18h total — muito curto","App Motorola básico","Autonomia fraca"],score:{"Som":76,"Conforto":76,"Autonomia":58,"Custo-Benefício":72,"Build":72},youtubeIds:["NMWYt5n4eZY","bH7_Qz3zVkk"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Motorola+Moto+Buds+500",ml:"https://lista.mercadolivre.com.br/motorola-moto-buds-500",official:"https://www.motorola.com.br"},
{id:412,name:"Motorola Moto Buds",brand:"Motorola",price:299,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+35h case","Recarga":"1.5h","ANC":"Sim (ANC básico)","Microfone":"2 mics","IPX":"IP54","Peso":"4.9g/fone","Codec":"SBC, AAC"},pros:["42h total — excelente","ANC incluído","IP54","BT 5.3","Design compacto"],cons:["Sem LDAC","ANC básico","App Motorola simples"],score:{"Som":70,"Conforto":74,"Autonomia":88,"Custo-Benefício":80,"Build":68},youtubeIds:["NMWYt5n4eZY","bH7_Qz3zVkk"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Motorola+Moto+Buds",ml:"https://lista.mercadolivre.com.br/motorola-moto-buds",official:"https://www.motorola.com.br"},
{id:413,name:"Motorola Moto Buds Loop",brand:"Motorola",price:199,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"8h+32h case","Recarga":"1h","ANC":"Não","Microfone":"2 mics ENC","IPX":"IP55","Peso":"4.5g/fone","Codec":"SBC, AAC"},pros:["40h total","IP55","8h por carga","BT 5.3","Preço acessível"],cons:["Sem ANC","Sem LDAC","App Motorola simples"],score:{"Som":66,"Conforto":72,"Autonomia":86,"Custo-Benefício":80,"Build":64},youtubeIds:["NMWYt5n4eZY","bH7_Qz3zVkk"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Motorola+Moto+Buds+Loop",ml:"https://lista.mercadolivre.com.br/motorola-moto-buds-loop",official:"https://www.motorola.com.br"},

// ── MULTILASER ────────────────────────────────────────────────────────────────
{id:420,name:"Multilaser PH390",brand:"Multilaser",price:149,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.1","Autonomia":"20h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"200g","Codec":"SBC"},pros:["Preço muito acessível","Dobrável","Marca brasileira com suporte local","Design colorido"],cons:["Sem ANC","Sem LDAC","Qualidade sonora básica","BT 5.1","Autonomia limitada"],score:{"Som":54,"Conforto":62,"Autonomia":70,"Custo-Benefício":76,"Build":52},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Multilaser+PH390",ml:"https://lista.mercadolivre.com.br/multilaser-ph390",official:"https://www.multilaser.com.br"},
{id:421,name:"Multilaser PH352",brand:"Multilaser",price:99,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.0","Autonomia":"4h+16h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"5g/fone","Codec":"SBC"},pros:["~R$99","IPX4","Marca brasileira","20h total","Controle por toque"],cons:["Sem ANC","Sem LDAC","BT 5.0","Qualidade básica","Autonomia curta"],score:{"Som":50,"Conforto":62,"Autonomia":60,"Custo-Benefício":72,"Build":48},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Multilaser+PH352",ml:"https://lista.mercadolivre.com.br/multilaser-ph352",official:"https://www.multilaser.com.br"},

// ── PHILCO ────────────────────────────────────────────────────────────────────
{id:425,name:"Philco PFO02BTG",brand:"Philco",price:129,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"20h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"190g","Codec":"SBC, AAC"},pros:["Preço acessível","Dobrável","Marca brasileira conhecida","Garantia local"],cons:["Sem ANC","Sem LDAC","Qualidade sonora básica","Autonomia limitada"],score:{"Som":54,"Conforto":64,"Autonomia":68,"Custo-Benefício":72,"Build":52},youtubeIds:["t6kqGQ-wYT8","xP3OdKLW4LA"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philco+fone+bluetooth",ml:"https://lista.mercadolivre.com.br/philco-fone-bluetooth",official:"https://www.philco.com.br"},
{id:426,name:"Philco PFO04BTRG",brand:"Philco",price:99,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.0","Autonomia":"4h+16h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"5.5g/fone","Codec":"SBC"},pros:["~R$99","IPX4","Marca brasileira","Controle por toque","20h total"],cons:["Sem ANC","Sem LDAC","Qualidade básica","BT 5.0"],score:{"Som":50,"Conforto":60,"Autonomia":60,"Custo-Benefício":70,"Build":46},youtubeIds:["t6kqGQ-wYT8","xP3OdKLW4LA"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philco+fone+tws",ml:"https://lista.mercadolivre.com.br/philco-fone-tws",official:"https://www.philco.com.br"},

// ── JAYBIRD ───────────────────────────────────────────────────────────────────
{id:430,name:"Jaybird Vista 2",brand:"Jaybird",price:799,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.0","Autonomia":"8h+24h case","Recarga":"2h","ANC":"Sim (SurroundSense)","Microfone":"3 mics beamforming","IPX":"IP68","Peso":"6.2g/fone","Codec":"SBC, AAC"},pros:["IP68 — imersão total em água","ANC SurroundSense inteligente","3 mics beamforming","32h total","Foco em esportes premium"],cons:["Sem LDAC","BT 5.0","Preço elevado para as specs","Driver 6mm"],score:{"Som":76,"Conforto":80,"Autonomia":78,"Custo-Benefício":68,"Build":88},youtubeIds:["yBDHUW3L5Ec","rJPa5VCKW9s"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Jaybird+Vista+2",ml:"https://lista.mercadolivre.com.br/jaybird-vista-2",official:"https://www.jaybirdsport.com"},
{id:431,name:"Jaybird Run XT",brand:"Jaybird",price:499,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.0","Autonomia":"4h+8h case","Recarga":"2h","ANC":"Não","Microfone":"2 mics","IPX":"IPX7","Peso":"5.5g/fone","Codec":"SBC, AAC"},pros:["IPX7","Encaixe esportivo seguro","Design minimalista","App Jaybird com EQ"],cons:["Autonomia muito curta (12h total)","Sem ANC","Sem LDAC","Driver 6mm"],score:{"Som":70,"Conforto":76,"Autonomia":52,"Custo-Benefício":64,"Build":80},youtubeIds:["yBDHUW3L5Ec","rJPa5VCKW9s"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Jaybird+Run+XT",ml:"https://lista.mercadolivre.com.br/jaybird-run-xt",official:"https://www.jaybirdsport.com"},

// ── TOZO ──────────────────────────────────────────────────────────────────────
{id:435,name:"Tozo T10",brand:"Tozo",price:129,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.3","Autonomia":"6h+18h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX8","Peso":"5g/fone","Codec":"SBC, AAC"},pros:["IPX8 — imersão em água até 1m","Preço muito acessível","24h total","BT 5.3","Custo-benefício via importação"],cons:["Sem ANC","Sem LDAC","Qualidade sonora básica","Suporte limitado no BR"],score:{"Som":60,"Conforto":66,"Autonomia":72,"Custo-Benefício":80,"Build":62},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Tozo+T10",ml:"https://lista.mercadolivre.com.br/tozo-t10",official:"https://www.tozostore.com"},
{id:436,name:"Tozo A3",brand:"Tozo",price:159,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"5.5h+22h case","Recarga":"1h","ANC":"Não","Microfone":"ENC","IPX":"IPX5","Peso":"3.6g/fone","Codec":"SBC, AAC"},pros:["3.6g — ultracompacto","27.5h total","BT 5.3","ENC chamadas","Design minimalista"],cons:["Sem ANC","Sem LDAC","Autonomia curta por carga","Suporte limitado no BR"],score:{"Som":62,"Conforto":74,"Autonomia":74,"Custo-Benefício":78,"Build":58},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Tozo+A3",ml:"https://lista.mercadolivre.com.br/tozo-a3",official:"https://www.tozostore.com"},
{id:437,name:"Tozo HT2",brand:"Tozo",price:249,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.3","Autonomia":"60h sem ANC/35h ANC","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"240g","Codec":"SBC, AAC"},pros:["60h sem ANC por preço baixo","ANC incluído","Dobrável","BT 5.3","Custo-benefício forte"],cons:["Sem LDAC","ANC básico","Suporte limitado no BR","App inexistente"],score:{"Som":66,"Conforto":72,"Autonomia":92,"Custo-Benefício":82,"Build":60},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Tozo+HT2",ml:"https://lista.mercadolivre.com.br/tozo-ht2",official:"https://www.tozostore.com"},

// ── UGREEN ────────────────────────────────────────────────────────────────────
{id:440,name:"Ugreen HiTune Max5C",brand:"Ugreen",price:499,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.3","Autonomia":"70h sem ANC/40h ANC","Recarga":"2h","ANC":"Sim","Microfone":"4 mics","Dobrável":"Sim","Peso":"260g","Codec":"SBC, AAC, LDAC, aptX Adaptive"},pros:["LDAC + aptX Adaptive — raro na faixa","70h sem ANC","ANC funcional","4 mics","Custo-benefício muito forte"],cons:["Marca ainda crescendo no BR","App básico","ANC intermediário","Build não premium"],score:{"Som":80,"Conforto":78,"Autonomia":96,"Custo-Benefício":88,"Build":68},youtubeIds:["5UBCnOC3tMk","KFAvUz1J5Ro"],youtubeLabels:["Review","LDAC Test"],amazon:"https://www.amazon.com.br/s?k=Ugreen+HiTune+Max5",ml:"https://lista.mercadolivre.com.br/ugreen-hitune-max5",official:"https://www.ugreen.com"},
{id:441,name:"Ugreen HiTune T3",brand:"Ugreen",price:199,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+28h case","Recarga":"1.5h","ANC":"Sim (35dB)","Microfone":"4 mics","IPX":"IPX5","Peso":"4.8g/fone","Codec":"SBC, AAC"},pros:["ANC 35dB por R$199","4 mics","IPX5","35h total","BT 5.3"],cons:["Sem LDAC","ANC básico","App mínimo","Marca crescendo no BR"],score:{"Som":66,"Conforto":70,"Autonomia":82,"Custo-Benefício":84,"Build":62},youtubeIds:["U8oiEjDWBOI","gznaBuYZW-s"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Ugreen+HiTune+T3",ml:"https://lista.mercadolivre.com.br/ugreen-hitune-t3",official:"https://www.ugreen.com"},

// ── TRONSMART ─────────────────────────────────────────────────────────────────
{id:445,name:"Tronsmart Apollo Bold",brand:"Tronsmart",price:299,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"40h sem ANC/25h ANC","Recarga":"2h","ANC":"Sim (3 modos)","Microfone":"4 mics","Dobrável":"Sim","Peso":"265g","Codec":"SBC, AAC, aptX"},pros:["ANC 3 modos","aptX","40h sem ANC","4 mics","Design premium para o preço"],cons:["Sem LDAC","BT 5.0","App básico","Build intermediário"],score:{"Som":72,"Conforto":74,"Autonomia":86,"Custo-Benefício":80,"Build":64},youtubeIds:["OWE3R4cQc9Q","KmNaFdBQpqQ"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Tronsmart+Apollo+Bold",ml:"https://lista.mercadolivre.com.br/tronsmart-apollo-bold",official:"https://www.tronsmart.com"},
{id:446,name:"Tronsmart Onyx Pure",brand:"Tronsmart",price:149,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+30h case","Recarga":"1.5h","ANC":"Não","Microfone":"4 mics ENC","IPX":"IPX5","Peso":"4.9g/fone","Codec":"SBC, AAC"},pros:["37h total","IPX5","4 mics ENC","BT 5.3","Custo-benefício ok"],cons:["Sem ANC","Sem LDAC","App básico","Marca nichada no BR"],score:{"Som":62,"Conforto":68,"Autonomia":82,"Custo-Benefício":80,"Build":58},youtubeIds:["nJxHRNcG2QI","4vLpIv_gFao"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Tronsmart+Onyx+Pure",ml:"https://lista.mercadolivre.com.br/tronsmart-onyx-pure",official:"https://www.tronsmart.com"},

// ── JLAB ──────────────────────────────────────────────────────────────────────
{id:450,name:"JLab JBuds ANC 3",brand:"JLab",price:299,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"9h+43h case","Recarga":"1.5h","ANC":"Sim (3 modos)","Microfone":"4 mics","IPX":"IP55","Peso":"5.5g/fone","Codec":"SBC, AAC"},pros:["52h total — excepcional","ANC 3 modos","IP55","4 mics","9h por carga","Custo-benefício forte"],cons:["Sem LDAC","App básico","Marca pouco conhecida no BR","ANC intermediário"],score:{"Som":70,"Conforto":72,"Autonomia":96,"Custo-Benefício":84,"Build":66},youtubeIds:["yOHRIqOJCNE","VZi2FxDa_aQ"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=JLab+JBuds+ANC+3",ml:"https://lista.mercadolivre.com.br/jlab-jbuds-anc",official:"https://www.jlab.com"},
{id:451,name:"JLab Studio Pro ANC",brand:"JLab",price:399,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.1","Autonomia":"50h sem ANC/25h ANC","Recarga":"2h","ANC":"Sim (3 modos)","Microfone":"4 mics","Dobrável":"Sim","Peso":"270g","Codec":"SBC, AAC"},pros:["50h sem ANC","ANC 3 modos","4 mics","Dobrável","Custo-benefício ok"],cons:["Sem LDAC","BT 5.1","App básico","ANC intermediário"],score:{"Som":70,"Conforto":74,"Autonomia":90,"Custo-Benefício":78,"Build":64},youtubeIds:["OWE3R4cQc9Q","KmNaFdBQpqQ"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=JLab+Studio+Pro+ANC",ml:"https://lista.mercadolivre.com.br/jlab-studio-pro-anc",official:"https://www.jlab.com"},
