// ============================================================
//  BATCH 2 — Xiaomi/Redmi, QCY, Edifier, Soundcore, Sennheiser
//  Modelos ativos no Brasil — Abril 2026
//  Cole antes do ]; no headphones.js
// ============================================================

// ── XIAOMI / REDMI ────────────────────────────────────────────────────────────
// Linha Redmi Buds 6
{id:200,name:"Redmi Buds 6 Pro",brand:"Xiaomi",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm+BA coaxial triplo","Bluetooth":"5.4","Autonomia":"9h+27h case","Recarga":"1.5h","ANC":"-52dB (3 modos)","Microfone":"3 mics","IPX":"IP54","Peso":"5.1g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC -52dB — excelente para o preço","Driver coaxial triplo único","LDAC Hi-Res","BT 5.4","36h total"],cons:["App melhor com Xiaomi","Transparência artificial","Build intermediário"],score:{"Som":84,"Conforto":80,"Autonomia":83,"Custo-Benefício":91,"Build":72},youtubeIds:["Gso4HQyAz5U","qlK15yE8xfc"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+6+Pro",ml:"https://lista.mercadolivre.com.br/redmi-buds-6-pro",official:"https://www.mi.com/br"},
{id:201,name:"Redmi Buds 6",brand:"Xiaomi",price:359,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"Dual Hi-Fi","Bluetooth":"5.4","Autonomia":"10h+32h case","Recarga":"1.5h","ANC":"Sim (3 modos)","Microfone":"Sim","IPX":"IP54","Peso":"4.9g/fone","Codec":"SBC, AAC, LDAC"},pros:["Dual driver Hi-Fi","LDAC","42h total","4 modos EQ","Multiponto 2 dispositivos"],cons:["App melhor com Xiaomi","Build intermediário","ANC abaixo do Pro"],score:{"Som":80,"Conforto":78,"Autonomia":86,"Custo-Benefício":88,"Build":70},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+6",ml:"https://lista.mercadolivre.com.br/redmi-buds-6",official:"https://www.mi.com/br"},
{id:202,name:"Redmi Buds 6 Lite",brand:"Xiaomi",price:199,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"12mm titânio","Bluetooth":"5.3","Autonomia":"7h+31h case","Recarga":"1.5h","ANC":"Sim (40dB dinâmico)","Microfone":"Duplo com IA","IPX":"IPX4","Peso":"4.2g/fone","Codec":"SBC, AAC"},pros:["ANC 40dB dinâmico por R$199","Driver titânio","IA em chamadas","38h total","Ultraleve 4.2g"],cons:["Sem LDAC","App básico","IPX4 apenas"],score:{"Som":72,"Conforto":74,"Autonomia":84,"Custo-Benefício":90,"Build":64},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+6+Lite",ml:"https://lista.mercadolivre.com.br/redmi-buds-6-lite",official:"https://www.mi.com/br"},
{id:203,name:"Redmi Buds 6 Active",brand:"Xiaomi",price:149,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"14.2mm","Bluetooth":"5.4","Autonomia":"6h+24h case","Recarga":"1h","ANC":"ENC apenas","Microfone":"Sim","IPX":"IPX5","Peso":"4.3g/fone","Codec":"SBC, AAC"},pros:["Driver 14.2mm — maior da linha","BT 5.4","IPX5","Google Fast Pair","30h total"],cons:["Sem ANC","Sem LDAC","App básico"],score:{"Som":68,"Conforto":72,"Autonomia":78,"Custo-Benefício":90,"Build":62},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+6+Active",ml:"https://lista.mercadolivre.com.br/redmi-buds-6-active",official:"https://www.mi.com/br"},
{id:204,name:"Redmi Buds 6 Play",brand:"Xiaomi",price:119,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+29h case","Recarga":"1.5h","ANC":"ENC IA em chamadas","Microfone":"Sim","IPX":"IPX4","Peso":"4.0g/fone","Codec":"SBC, AAC"},pros:["Preço ~R$119","ENC IA em chamadas","36h total","Google Fast Pair","Ultraleve 4g"],cons:["Sem ANC","Sem LDAC","Driver 10mm básico"],score:{"Som":62,"Conforto":70,"Autonomia":80,"Custo-Benefício":90,"Build":58},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+6+Play",ml:"https://lista.mercadolivre.com.br/redmi-buds-6-play",official:"https://www.mi.com/br"},
// Linha Redmi Buds 5
{id:205,name:"Redmi Buds 5 Pro",brand:"Xiaomi",price:420,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm+tweeter cerâmica","Bluetooth":"5.3","Autonomia":"9h+38h case","Recarga":"1.5h","ANC":"-52dB (3 modos)","Microfone":"3 mics","IPX":"IP54","Peso":"5.6g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC -52dB excelente","Driver híbrido","LDAC Hi-Res","Estojo couro vegano","Hi-Res Audio certificado"],cons:["Não lançado oficialmente no BR (sem garantia oficial)","App melhor com Xiaomi","Build intermediário"],score:{"Som":82,"Conforto":80,"Autonomia":86,"Custo-Benefício":88,"Build":70},youtubeIds:["j4bE5lqFBWI","jcQYS5XZSUM"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+5+Pro",ml:"https://lista.mercadolivre.com.br/redmi-buds-5-pro",official:"https://www.mi.com/br"},
{id:206,name:"Redmi Buds 5",brand:"Xiaomi",price:249,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"12.4mm titânio","Bluetooth":"5.3","Autonomia":"10h+30h case","Recarga":"1h","ANC":"-46dB (3 modos)","Microfone":"3 mics","IPX":"IP54","Peso":"4.8g/fone","Codec":"SBC, AAC"},pros:["ANC -46dB por R$249","Driver titânio 12.4mm","IP54","40h total","3 modos transparência"],cons:["Sem LDAC","App melhor com Xiaomi","Build plástico"],score:{"Som":76,"Conforto":78,"Autonomia":84,"Custo-Benefício":90,"Build":66},youtubeIds:["j4bE5lqFBWI","jcQYS5XZSUM"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+5",ml:"https://lista.mercadolivre.com.br/redmi-buds-5",official:"https://www.mi.com/br"},
// Linha Xiaomi Buds
{id:207,name:"Xiaomi Buds 5",brand:"Xiaomi",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"12.4mm titânio","Bluetooth":"5.3","Autonomia":"10h+30h case","Recarga":"1h","ANC":"Sim (40dB, 3 modos)","Microfone":"Sim","IPX":"IPX4","Peso":"4.8g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC 40dB com 3 modos","Driver titânio","LDAC","Transparência eficaz","Design premium Xiaomi"],cons:["App melhor com Xiaomi","Bass intenso","IPX4"],score:{"Som":80,"Conforto":78,"Autonomia":84,"Custo-Benefício":87,"Build":74},youtubeIds:["vIFlpSNpIdM","l-NrWL4VRHY"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Xiaomi+Buds+5",ml:"https://lista.mercadolivre.com.br/xiaomi-buds-5",official:"https://www.mi.com/br"},
// Linha Redmi Buds 4
{id:208,name:"Redmi Buds 4 Pro",brand:"Xiaomi",price:299,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"9h+27h case","Recarga":"1.5h","ANC":"-43dB adaptativo","Microfone":"3 mics","IPX":"IP54","Peso":"4.9g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC -43dB adaptativo","LDAC","IP54","36h total","Multiconexão 2 dispositivos"],cons:["App melhor com Xiaomi","Bass excessivo","Geração anterior"],score:{"Som":78,"Conforto":76,"Autonomia":82,"Custo-Benefício":88,"Build":68},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+4+Pro",ml:"https://lista.mercadolivre.com.br/redmi-buds-4-pro",official:"https://www.mi.com/br"},
{id:209,name:"Redmi Buds 4 Lite",brand:"Xiaomi",price:99,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"12mm","Bluetooth":"5.3","Autonomia":"5h+20h case","Recarga":"1.5h","ANC":"Não","Microfone":"ENC","IPX":"IP54","Peso":"4.4g/fone","Codec":"SBC, AAC"},pros:["~R$99 — mais barato do catálogo","Driver 12mm generoso","IP54","Google Fast Pair","Leve 4.4g"],cons:["Sem ANC","Sem LDAC","25h total — curto","App básico"],score:{"Som":60,"Conforto":70,"Autonomia":68,"Custo-Benefício":88,"Build":58},youtubeIds:["FQNBA5RO0HI","7cJVB9bS5FM"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Redmi+Buds+4+Lite",ml:"https://lista.mercadolivre.com.br/redmi-buds-4-lite",official:"https://www.mi.com/br"},
// Xiaomi Air 3 SE
{id:210,name:"Xiaomi Air 3 SE",brand:"Xiaomi",price:179,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"6h+24h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"4.4g/fone","Codec":"SBC, AAC"},pros:["Design semi-auricular open-fit","Confortável sem ponteira","BT 5.3","30h total","Custo-benefício ok"],cons:["Sem ANC","Sem LDAC","Menos isolamento que in-ear"],score:{"Som":64,"Conforto":78,"Autonomia":76,"Custo-Benefício":84,"Build":62},youtubeIds:["vIFlpSNpIdM","l-NrWL4VRHY"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Xiaomi+Air+3+SE",ml:"https://lista.mercadolivre.com.br/xiaomi-air-3-se",official:"https://www.mi.com/br"},

// ── QCY ───────────────────────────────────────────────────────────────────────
// Over-ear
{id:220,name:"QCY H3 Pro",brand:"QCY",price:349,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm titânio","Bluetooth":"5.4","Autonomia":"55h sem ANC/40h ANC","Recarga":"2h","ANC":"Sim (adaptativo, 3 modos)","Microfone":"Sim","Dobrável":"Sim","IPX":"IPX5","Codec":"SBC, AAC, LDAC"},pros:["LDAC por preço acessível","ANC adaptativo","55h sem ANC","IPX5","Multiponto","Entrada P2"],cons:["App básico","Build não premium","ANC adaptativo não é o mais forte"],score:{"Som":79,"Conforto":76,"Autonomia":94,"Custo-Benefício":90,"Build":68},youtubeIds:["vBMuJVKFo8E","yGpHM2T3K3E"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=QCY+H3+Pro",ml:"https://lista.mercadolivre.com.br/qcy-h3-pro",official:"https://www.qcy.com"},
{id:221,name:"QCY H3 ANC",brand:"QCY",price:239,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm titânio","Bluetooth":"5.3","Autonomia":"60h sem ANC/35h ANC","Recarga":"2h","ANC":"Sim (43dB)","Microfone":"6 mics","Dobrável":"Sim","IPX":"IPX5","Codec":"SBC, AAC, LDAC"},pros:["60h — entre as maiores do mercado","LDAC por R$239","ANC funcional","IPX5","Entrada P2","6 microfones"],cons:["ANC 43dB — intermediário","App básico","Build não premium"],score:{"Som":78,"Conforto":76,"Autonomia":97,"Custo-Benefício":92,"Build":66},youtubeIds:["vBMuJVKFo8E","yGpHM2T3K3E"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=QCY+H3+ANC",ml:"https://lista.mercadolivre.com.br/qcy-h3-anc",official:"https://www.qcy.com"},
{id:222,name:"QCY H3S ANC",brand:"QCY",price:399,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.3","Autonomia":"100h+","Recarga":"2h","ANC":"Sim (56dB declarado)","Microfone":"Sim","Dobrável":"Sim","IPX":"IPX5","Codec":"SBC, AAC, LDAC"},pros:["100h+ — recorde absoluto do mercado","LDAC","IPX5","ANC eficaz"],cons:["ANC real ~45dB em testes independentes","App básico","Build não premium"],score:{"Som":79,"Conforto":78,"Autonomia":99,"Custo-Benefício":90,"Build":68},youtubeIds:["YX6ywt5M6oo","zy5bVn33xHk"],youtubeLabels:["Review","ANC Real Test"],amazon:"https://www.amazon.com.br/s?k=QCY+H3S",ml:"https://lista.mercadolivre.com.br/qcy-h3s",official:"https://www.qcy.com"},
{id:223,name:"QCY MeloBuds H2 Pro",brand:"QCY",price:299,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.3","Autonomia":"80h sem ANC","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","IPX":"IPX4","Codec":"SBC, AAC"},pros:["80h de autonomia","Almofadas espuma proteína","Design premium","Leve e dobrável","Custo-benefício"],cons:["Sem ANC","Sem LDAC","IPX4 básico"],score:{"Som":74,"Conforto":82,"Autonomia":97,"Custo-Benefício":86,"Build":68},youtubeIds:["vBMuJVKFo8E","yGpHM2T3K3E"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=QCY+MeloBuds+H2+Pro",ml:"https://lista.mercadolivre.com.br/qcy-melobuds-h2-pro",official:"https://www.qcy.com"},
// TWS
{id:224,name:"QCY HT08 MeloBuds Pro",brand:"QCY",price:229,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm+BA","Bluetooth":"5.3","Autonomia":"7h+27h case","Recarga":"1.5h","ANC":"Sim (46dB adaptativo)","Microfone":"6 mics","IPX":"IPX5","Peso":"5.2g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC 46dB adaptativo","LDAC + driver híbrido","6 mics com IA","34h total","IPX5","Anatel homologado"],cons:["App básico","ANC declarado x real pode variar","Build intermediário"],score:{"Som":78,"Conforto":74,"Autonomia":82,"Custo-Benefício":90,"Build":66},youtubeIds:["UwqvBmXLm3g","ZK_CJv8BfEk"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=QCY+HT08",ml:"https://lista.mercadolivre.com.br/qcy-ht08",official:"https://www.qcy.com"},
{id:225,name:"QCY HT05 MeloBuds ANC",brand:"QCY",price:159,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.2","Autonomia":"7.5h+22.5h case","Recarga":"1.5h","ANC":"Sim (40dB, 3 modos)","Microfone":"6 mics","IPX":"IPX5","Peso":"5.1g/fone","Codec":"SBC, AAC"},pros:["ANC 40dB por R$159","6 mics","IPX5","30h total","Avaliações excelentes na Amazon"],cons:["Sem LDAC","Durabilidade questionada por alguns","App básico"],score:{"Som":67,"Conforto":70,"Autonomia":78,"Custo-Benefício":92,"Build":60},youtubeIds:["UwqvBmXLm3g","ZK_CJv8BfEk"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=QCY+HT05",ml:"https://lista.mercadolivre.com.br/qcy-ht05",official:"https://www.qcy.com"},
{id:226,name:"QCY T20",brand:"QCY",price:129,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"13mm LCP","Bluetooth":"5.3","Autonomia":"5.5h+20.5h case","Recarga":"1.5h","ANC":"Não","Microfone":"4 mics","IPX":"IPX4","Peso":"5.0g/fone","Codec":"SBC, AAC"},pros:["Semi in-ear confortável — sem ponteira","Driver 13mm LCP","Latência 68ms para games","IPX4","Design diferente"],cons:["Sem ANC","Sem LDAC","Autonomia curta (26h total)"],score:{"Som":66,"Conforto":74,"Autonomia":72,"Custo-Benefício":86,"Build":60},youtubeIds:["cHUfHl4I8BA","GjAoMqPWuCA"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=QCY+T20",ml:"https://lista.mercadolivre.com.br/qcy-t20",official:"https://www.qcy.com"},
{id:227,name:"QCY T13",brand:"QCY",price:99,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.1","Autonomia":"7h+33h case","Recarga":"1.5h","ANC":"Não","Microfone":"4 mics","IPX":"IPX4","Peso":"4.8g/fone","Codec":"SBC, AAC"},pros:["~R$99 — excelente custo-benefício","4 mics chamadas nítidas","40h total","Carga 10min=1h","App com EQ"],cons:["Sem ANC","Sem LDAC","BT 5.1","Graves medianos"],score:{"Som":65,"Conforto":70,"Autonomia":85,"Custo-Benefício":93,"Build":60},youtubeIds:["yOHRIqOJCNE","VZi2FxDa_aQ"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=QCY+T13",ml:"https://lista.mercadolivre.com.br/qcy-t13",official:"https://www.qcy.com"},

// ── EDIFIER ───────────────────────────────────────────────────────────────────
// Over-ear
{id:230,name:"Edifier W830NB",brand:"Edifier",price:549,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm Hi-Res titânio","Bluetooth":"5.4","Autonomia":"94h sem ANC/60h ANC","Recarga":"2h","ANC":"Sim (Híbrido)","Microfone":"Sim","Dobrável":"Sim","Peso":"258g","Codec":"SBC, AAC, LDAC"},pros:["94h sem ANC — recorde entre headphones LDAC","LDAC Hi-Res","BT 5.4","ANC híbrido","Dobrável"],cons:["Sem multiponto","Build intermediário","Pesado 258g"],score:{"Som":83,"Conforto":80,"Autonomia":99,"Custo-Benefício":88,"Build":72},youtubeIds:["OIUlADhfxN8","rKAm7fOEhww"],youtubeLabels:["Review","LDAC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+W830NB",ml:"https://lista.mercadolivre.com.br/edifier-w830nb",official:"https://www.edifier.com.br"},
{id:231,name:"Edifier W820NB Plus (V25)",brand:"Edifier",price:499,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm titânio","Bluetooth":"6.1","Autonomia":"88h sem ANC","Recarga":"2h/15min=15h","ANC":"Sim (-49dB, IA)","Microfone":"Sim (IA)","Dobrável":"Sim","Peso":"237g","Codec":"SBC, AAC, LDAC"},pros:["LDAC + ANC -49dB + BT 6.1","88h de autonomia","Carregamento rápido 15min=15h","Filtro IA para chamadas","Som espacial"],cons:["BT 6.1 ainda em maturação","Sem multiponto","Build intermediário"],score:{"Som":84,"Conforto":80,"Autonomia":98,"Custo-Benefício":88,"Build":74},youtubeIds:["SkXNMXcIlYA","yqSBaS7sT2I"],youtubeLabels:["Review","LDAC+ANC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+W820NB+Plus",ml:"https://lista.mercadolivre.com.br/edifier-w820nb-plus",official:"https://www.edifier.com.br"},
{id:232,name:"Edifier W820NB",brand:"Edifier",price:349,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm Hi-Res","Bluetooth":"5.0","Autonomia":"49h sem ANC/29h ANC","Recarga":"2h","ANC":"Sim (Híbrido, rede neural)","Microfone":"Sim","Dobrável":"Sim","Peso":"230g","Codec":"SBC, AAC, LDAC"},pros:["LDAC+Hi-Res por R$349","ANC híbrido com rede neural","49h sem ANC","Referência custo-benefício da categoria","Modo gamer"],cons:["Sem multiponto","BT 5.0","Hi-Res só no cabo"],score:{"Som":80,"Conforto":79,"Autonomia":90,"Custo-Benefício":92,"Build":70},youtubeIds:["SkXNMXcIlYA","yqSBaS7sT2I"],youtubeLabels:["Review","ANC+LDAC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+W820NB",ml:"https://lista.mercadolivre.com.br/edifier-w820nb",official:"https://www.edifier.com.br"},
{id:233,name:"Edifier W800BT Plus",brand:"Edifier",price:249,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.1","Autonomia":"55h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"210g","Codec":"SBC, AAC"},pros:["55h por preço baixo","Cabo P2 disponível","Dobrável","Custo-benefício sólido"],cons:["Sem ANC","Sem LDAC","BT 5.1"],score:{"Som":66,"Conforto":72,"Autonomia":94,"Custo-Benefício":88,"Build":60},youtubeIds:["MDYH3KJXDSA","dFpCU6YYZKY"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Edifier+W800BT+Plus",ml:"https://lista.mercadolivre.com.br/edifier-w800bt-plus",official:"https://www.edifier.com.br"},
// TWS Edifier
{id:234,name:"Edifier NeoDots",brand:"Edifier",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"10mm titânio","Bluetooth":"5.4","Autonomia":"8h+32h case","Recarga":"1.5h","ANC":"Sim (48dB)","Microfone":"Sim","IPX":"IPX5","Peso":"5.2g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC 48dB — um dos maiores em TWS","Driver titânio","LDAC","40h total","BT 5.4","IPX5"],cons:["App limitado","ANC pode sobrar para alguns ambientes","Build intermediário"],score:{"Som":78,"Conforto":76,"Autonomia":84,"Custo-Benefício":84,"Build":74},youtubeIds:["A8rV-P4vCq4","q8NTJVO5blE"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+NeoDots",ml:"https://lista.mercadolivre.com.br/edifier-neodots",official:"https://www.edifier.com.br"},
{id:235,name:"Edifier TWS1 Pro 2",brand:"Edifier",price:279,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"6mm BA","Bluetooth":"5.3","Autonomia":"6h+36h case","Recarga":"1.5h","ANC":"Sim (42dB)","Microfone":"Sim","IPX":"IPX5","Peso":"5.5g/fone","Codec":"SBC, AAC, aptX"},pros:["ANC 42dB + modo ambiente","Driver Balanced Armature","aptX","IPX5","42h total"],cons:["Driver BA 6mm — graves mais fracos","App simples","Sem LDAC"],score:{"Som":75,"Conforto":72,"Autonomia":82,"Custo-Benefício":88,"Build":66},youtubeIds:["1OQjuDXm7qg","Mk47vTMnMaA"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+TWS1+Pro+2",ml:"https://lista.mercadolivre.com.br/edifier-tws1-pro-2",official:"https://www.edifier.com.br"},
{id:236,name:"Edifier TWS NB2 Pro",brand:"Edifier",price:349,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"6mm BA","Bluetooth":"5.0","Autonomia":"7h+21h case","Recarga":"2h","ANC":"Sim (42dB)","Microfone":"4 mics","IPX":"IPX5","Peso":"6.5g/fone","Codec":"SBC, AAC, aptX"},pros:["ANC 42dB + modo ambiente","Driver BA","aptX","IPX5","4 mics"],cons:["BT 5.0","28h total abaixo da concorrência","App simples"],score:{"Som":75,"Conforto":74,"Autonomia":74,"Custo-Benefício":80,"Build":68},youtubeIds:["1OQjuDXm7qg","Mk47vTMnMaA"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Edifier+NB2+Pro",ml:"https://lista.mercadolivre.com.br/edifier-nb2-pro",official:"https://www.edifier.com.br"},

// ── SOUNDCORE (ANKER) ─────────────────────────────────────────────────────────
// Over-ear
{id:240,name:"Soundcore Space One Pro",brand:"Anker",price:499,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.3","Autonomia":"60h sem ANC","Recarga":"2h","ANC":"Sim (adaptativo, 6 mics)","Microfone":"6 mics","Dobrável":"Sim","IPX":"Não","Codec":"SBC, AAC, LDAC"},pros:["6 mics + ANC adaptativo","LDAC","60h sem ANC","App com EQ 22 bandas","Conexão multiponto"],cons:["Sem certificação IPX","App pode ter bugs","ANC abaixo do premium"],score:{"Som":82,"Conforto":82,"Autonomia":93,"Custo-Benefício":86,"Build":74},youtubeIds:["5UBCnOC3tMk","KFAvUz1J5Ro"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Space+One+Pro",ml:"https://lista.mercadolivre.com.br/soundcore-space-one-pro",official:"https://www.soundcore.com"},
{id:241,name:"Soundcore Space Q45",brand:"Anker",price:449,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm Hi-Res titânio","Bluetooth":"5.3","Autonomia":"65h sem ANC/50h ANC","Recarga":"4h","ANC":"Sim (adaptativo, 3 modos)","Microfone":"4 mics","Dobrável":"Sim","Peso":"265g","Codec":"SBC, AAC, LDAC"},pros:["65h sem ANC","ANC 3 modos","LDAC Hi-Res","EQ 22 bandas no app","Custo-benefício forte"],cons:["ANC abaixo XM5","Transparência artificial","App variável"],score:{"Som":81,"Conforto":82,"Autonomia":93,"Custo-Benefício":87,"Build":72},youtubeIds:["5UBCnOC3tMk","KFAvUz1J5Ro"],youtubeLabels:["Review","vs Sony XM5"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Space+Q45",ml:"https://lista.mercadolivre.com.br/soundcore-space-q45",official:"https://www.soundcore.com"},
{id:242,name:"Soundcore Q45",brand:"Anker",price:299,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm Hi-Res","Bluetooth":"5.3","Autonomia":"50h sem ANC/40h ANC","Recarga":"4h","ANC":"Sim (adaptativo)","Microfone":"2 mics","Dobrável":"Sim","Peso":"253g","Codec":"SBC, AAC, LDAC"},pros:["ANC adaptativo eficiente","LDAC Hi-Res","EQ 22 bandas","50h sem ANC","Confortável em sessões longas"],cons:["ANC abaixo do premium","Transparência artificial","Sem certificação IP"],score:{"Som":80,"Conforto":82,"Autonomia":88,"Custo-Benefício":85,"Build":70},youtubeIds:["OWE3R4cQc9Q","KmNaFdBQpqQ"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Q45",ml:"https://lista.mercadolivre.com.br/soundcore-q45",official:"https://www.soundcore.com"},
{id:243,name:"Soundcore Q30",brand:"Anker",price:199,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm Hi-Res","Bluetooth":"5.0","Autonomia":"60h sem ANC/40h ANC","Recarga":"5h","ANC":"Sim (3 modos)","Microfone":"Sim","Dobrável":"Sim","Peso":"269g","Codec":"SBC, AAC"},pros:["60h sem ANC","ANC 3 modos por R$199","Hi-Res Audio","Dobrável","App Soundcore"],cons:["Sem LDAC","BT 5.0","Carregamento lento (5h)","ANC básico"],score:{"Som":74,"Conforto":74,"Autonomia":92,"Custo-Benefício":88,"Build":64},youtubeIds:["OWE3R4cQc9Q","KmNaFdBQpqQ"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Q30",ml:"https://lista.mercadolivre.com.br/soundcore-q30",official:"https://www.soundcore.com"},
{id:244,name:"Soundcore Q11i",brand:"Anker",price:199,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm Hi-Res","Bluetooth":"5.3","Autonomia":"60h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"260g","Codec":"SBC, AAC"},pros:["60h de autonomia","Hi-Res Audio","BT 5.3","Almofadas removíveis e laváveis","Multiponto 2 dispositivos"],cons:["Sem ANC","Sem LDAC","Design simples"],score:{"Som":72,"Conforto":76,"Autonomia":92,"Custo-Benefício":86,"Build":64},youtubeIds:["OWE3R4cQc9Q","KmNaFdBQpqQ"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Q11i",ml:"https://lista.mercadolivre.com.br/soundcore-q11i",official:"https://www.soundcore.com"},
// TWS Soundcore
{id:245,name:"Soundcore Liberty 4 NC",brand:"Anker",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm+BA","Bluetooth":"5.3","Autonomia":"10h+40h case","Recarga":"1.5h","ANC":"Sim (98.5%, adaptativo)","Microfone":"6 mics","IPX":"IP55","Peso":"5.5g/fone","Codec":"SBC, AAC, LDAC"},pros:["ANC 98.5% impressionante","Driver híbrido","LDAC","50h total","IP55","EQ personalizado por ouvido"],cons:["App com bugs ocasionais","Marca em construção no BR","Case volumoso"],score:{"Som":82,"Conforto":80,"Autonomia":90,"Custo-Benefício":88,"Build":74},youtubeIds:["CBRT2N7RMIU","MPKK9mLZVzg"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Liberty+4+NC",ml:"https://lista.mercadolivre.com.br/soundcore-liberty-4-nc",official:"https://www.soundcore.com"},
{id:246,name:"Soundcore Space A40",brand:"Anker",price:299,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm","Bluetooth":"5.2","Autonomia":"10h+40h case","Recarga":"2h","ANC":"Sim (adaptativo)","Microfone":"4 mics","IPX":"IPX4","Peso":"5.3g/fone","Codec":"SBC, AAC, LDAC"},pros:["50h total","LDAC barato","ANC adaptativo","Carga 10min=3h","Compacto"],cons:["IPX4 básico","App variável","ANC intermediário"],score:{"Som":79,"Conforto":78,"Autonomia":91,"Custo-Benefício":90,"Build":70},youtubeIds:["U8oiEjDWBOI","gznaBuYZW-s"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Space+A40",ml:"https://lista.mercadolivre.com.br/soundcore-space-a40",official:"https://www.soundcore.com"},
{id:247,name:"Soundcore P30i",brand:"Anker",price:189,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm BassUp","Bluetooth":"5.4","Autonomia":"7h+38h case","Recarga":"1.5h/10min=2h","ANC":"Sim (42dB adaptativo)","Microfone":"4 mics + IA","IPX":"IP54","Peso":"5.6g/fone","Codec":"SBC, AAC"},pros:["ANC 42dB adaptativo por R$189","Estojo com suporte de celular — único","45h total","IP54","4 mics + IA"],cons:["Sem LDAC","Case volumoso","ANC básico"],score:{"Som":70,"Conforto":72,"Autonomia":88,"Custo-Benefício":90,"Build":64},youtubeIds:["yE1f6O-Pm0A","ZFPqnFf9n_Y"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Soundcore+P30i",ml:"https://lista.mercadolivre.com.br/soundcore-p30i",official:"https://www.soundcore.com"},
{id:248,name:"Soundcore P31i",brand:"Anker",price:349,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm","Bluetooth":"5.4","Autonomia":"8h+42h case","Recarga":"1.5h","ANC":"Sim (adaptativo)","Microfone":"4 mics + IA","IPX":"IP55","Peso":"5.8g/fone","Codec":"SBC, AAC, LDAC"},pros:["Tradução em tempo real integrada — inédito","LDAC","50h total","IP55","Áudio espacial","ANC adaptativo"],cons:["Tradução depende de conectividade","App necessário para tradução","Build intermediário"],score:{"Som":78,"Conforto":76,"Autonomia":90,"Custo-Benefício":84,"Build":72},youtubeIds:["yE1f6O-Pm0A","ZFPqnFf9n_Y"],youtubeLabels:["Review","Tradução Demo"],amazon:"https://www.amazon.com.br/s?k=Soundcore+P31i",ml:"https://lista.mercadolivre.com.br/soundcore-p31i",official:"https://www.soundcore.com"},
// Esportivos Soundcore
{id:249,name:"Soundcore Sport X20",brand:"Anker",price:299,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"9h+39h case","Recarga":"1.5h","ANC":"Sim (adaptativo)","Microfone":"Sim","IPX":"IP68","Peso":"7.6g/fone","Codec":"SBC, AAC"},pros:["IP68 + ANC — raro em esportivos","Ganchos ajustáveis","48h total","Graves intensos","Ideal para treino/natação"],cons:["Sem LDAC","Volumoso para uso casual","App básico"],score:{"Som":72,"Conforto":76,"Autonomia":90,"Custo-Benefício":82,"Build":86},youtubeIds:["U8oiEjDWBOI","gznaBuYZW-s"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Soundcore+Sport+X20",ml:"https://lista.mercadolivre.com.br/soundcore-sport-x20",official:"https://www.soundcore.com"},

// ── SENNHEISER ────────────────────────────────────────────────────────────────
// Over-ear Momentum
{id:250,name:"Sennheiser Momentum 4 Wireless",brand:"Sennheiser",price:1699,tier:"premium",type:"Over-ear",specs:{"Driver":"42mm","Bluetooth":"5.2","Autonomia":"60h ANC","Recarga":"2h/5min=4h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics TrueVoice","Dobrável":"Sim","Peso":"293g","Codec":"SBC, AAC, aptX Adaptive, LC3"},pros:["60h com ANC — recorde entre premium","aptX Adaptive+LC3/LE Audio","Qualidade audiófila Sennheiser","ANC adaptativo eficiente","Dobrável","Carga rápida"],cons:["Sem LDAC","Preço premium","Pesado 293g"],score:{"Som":93,"Conforto":86,"Autonomia":96,"Custo-Benefício":74,"Build":84},youtubeIds:["DKbvUMHEFOg","VTx8EWIqpNE"],youtubeLabels:["Review","vs Sony XM5"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Momentum+4",ml:"https://lista.mercadolivre.com.br/sennheiser-momentum-4",official:"https://br.sennheiser-hearing.com"},
// Over-ear Accentum
{id:251,name:"Sennheiser Accentum Plus Wireless",brand:"Sennheiser",price:999,tier:"premium",type:"Over-ear",specs:{"Driver":"37mm","Bluetooth":"5.2","Autonomia":"50h ANC","Recarga":"3h/5min=5h","ANC":"Sim (Adaptive ANC)","Microfone":"Sim","Dobrável":"Sim","Peso":"233g","Codec":"SBC, AAC, aptX Adaptive"},pros:["50h com ANC — excelente","aptX Adaptive","ANC adaptativo","Multiponto 2 dispositivos","Entrada P2","Mais barato que o Momentum 4"],cons:["Sem LDAC","Construção plástica vs Momentum","Sem LC3"],score:{"Som":88,"Conforto":84,"Autonomia":90,"Custo-Benefício":80,"Build":80},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","vs Momentum 4"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Accentum+Plus",ml:"https://lista.mercadolivre.com.br/sennheiser-accentum-plus",official:"https://br.sennheiser-hearing.com"},
{id:252,name:"Sennheiser Accentum Wireless",brand:"Sennheiser",price:799,tier:"mid",type:"Over-ear",specs:{"Driver":"37mm","Bluetooth":"5.2","Autonomia":"50h ANC","Recarga":"3h/10min=5h","ANC":"Sim (Adaptive ANC)","Microfone":"Sim","Dobrável":"Sim","Peso":"233g","Codec":"SBC, AAC, aptX HD"},pros:["50h com ANC — excelente","ANC adaptativo Sennheiser","aptX HD","Custo-benefício Sennheiser","Carga rápida"],cons:["Sem LDAC ou aptX Adaptive","Construção mais plástica","App básico vs Momentum"],score:{"Som":85,"Conforto":82,"Autonomia":90,"Custo-Benefício":80,"Build":76},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","Sound Quality"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Accentum+Wireless",ml:"https://lista.mercadolivre.com.br/sennheiser-accentum-wireless",official:"https://br.sennheiser-hearing.com"},
{id:253,name:"Sennheiser HD 450BT",brand:"Sennheiser",price:699,tier:"mid",type:"Over-ear",specs:{"Driver":"38mm","Bluetooth":"5.0","Autonomia":"30h ANC","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"233g","Codec":"SBC, AAC, aptX, aptX LL"},pros:["Som Sennheiser referência","aptX LL para vídeo (baixa latência)","ANC eficiente","Dobrável","Preço mais acessível da linha"],cons:["Sem LDAC","30h — abaixo dos concorrentes atuais","Design discreto"],score:{"Som":85,"Conforto":82,"Autonomia":76,"Custo-Benefício":78,"Build":76},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","Sound Quality"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+HD+450BT",ml:"https://lista.mercadolivre.com.br/sennheiser-hd-450bt",official:"https://br.sennheiser-hearing.com"},
// TWS Momentum
{id:254,name:"Sennheiser Momentum True Wireless 4",brand:"Sennheiser",price:1999,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"7mm","Bluetooth":"5.4","Autonomia":"7.5h+30h case","Recarga":"1.5h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","IPX":"IP54","Peso":"5.4g/fone","Codec":"SBC, AAC, aptX Lossless, LC3, Auracast"},pros:["aptX Lossless — qualidade CD sem perdas","Auracast / LE Audio","BT 5.4","ANC adaptativo","Qualidade audiófila","Chip Qualcomm S5 Gen 2"],cons:["Preço muito elevado","Sem LDAC","Autonomia moderada (37.5h total)"],score:{"Som":93,"Conforto":84,"Autonomia":78,"Custo-Benefício":64,"Build":88},youtubeIds:["VXXJ67TsDuQ","mj9zTGhzF10"],youtubeLabels:["Review","Sound Quality"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Momentum+True+Wireless+4",ml:"https://lista.mercadolivre.com.br/sennheiser-momentum-tws-4",official:"https://br.sennheiser-hearing.com"},
{id:255,name:"Sennheiser Momentum True Wireless 3",brand:"Sennheiser",price:1499,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"7mm dinâmico","Bluetooth":"5.2","Autonomia":"7h+21h case","Recarga":"1.5h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","IPX":"IPX4","Peso":"5.4g/fone","Codec":"SBC, AAC, aptX, aptX Adaptive"},pros:["ANC adaptativo de qualidade","aptX Adaptive","Qualidade audiófila Sennheiser","App Smart Control completo","Som natural e equilibrado"],cons:["28h total abaixo dos concorrentes","Geração anterior ao TW4","Preço elevado","Sem LDAC"],score:{"Som":90,"Conforto":84,"Autonomia":72,"Custo-Benefício":68,"Build":86},youtubeIds:["VXXJ67TsDuQ","mj9zTGhzF10"],youtubeLabels:["Review","vs TW4"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Momentum+True+Wireless+3",ml:"https://lista.mercadolivre.com.br/sennheiser-momentum-tws-3",official:"https://br.sennheiser-hearing.com"},
{id:256,name:"Sennheiser Accentum True Wireless",brand:"Sennheiser",price:999,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"7mm","Bluetooth":"5.2","Autonomia":"5h+20h case","Recarga":"1.5h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","IPX":"IPX4","Peso":"5g/fone","Codec":"SBC, AAC, aptX"},pros:["ANC adaptativo Sennheiser","Design elegante premiado Red Dot","Som neutro e preciso","Mais barato que o MTW 4","App Smart Control"],cons:["25h total — curto","Sem LDAC ou aptX Adaptive","Preço ainda elevado"],score:{"Som":86,"Conforto":82,"Autonomia":65,"Custo-Benefício":68,"Build":84},youtubeIds:["VXXJ67TsDuQ","mj9zTGhzF10"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Accentum+True+Wireless",ml:"https://lista.mercadolivre.com.br/sennheiser-accentum-tws",official:"https://br.sennheiser-hearing.com"},
// Esportivo
{id:257,name:"Sennheiser Momentum Sport",brand:"Sennheiser",price:1599,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"7mm","Bluetooth":"5.2","Autonomia":"6h+18h case","Recarga":"1.5h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","IPX":"IPX55","Peso":"6.2g/fone","Codec":"SBC, AAC, aptX Adaptive"},pros:["Sensor de frequência cardíaca e temperatura corporal — único","Integração Polar/Apple Health/Garmin","ANC adaptativo","aptX Adaptive","IPX55"],cons:["Preço muito elevado","24h total — curto","Foco em esporte — menos versátil","Sem LDAC"],score:{"Som":88,"Conforto":80,"Autonomia":66,"Custo-Benefício":62,"Build":86},youtubeIds:["DKbvUMHEFOg","VTx8EWIqpNE"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Sennheiser+Momentum+Sport",ml:"https://lista.mercadolivre.com.br/sennheiser-momentum-sport",official:"https://br.sennheiser-hearing.com"},
