// ============================================================
//  BATCH 3 — Jabra, Philips, Shokz, Haylou, Baseus, Lenovo,
//             Bang & Olufsen, AKG
//  Modelos ativos no Brasil — Abril 2026
//  Cole antes do ]; no headphones.js
// ============================================================

// ── JABRA ─────────────────────────────────────────────────────────────────────
{id:300,name:"Jabra Elite 10 (2ª geração)",brand:"Jabra",price:1799,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"12mm","Bluetooth":"5.3","Autonomia":"10h+28h case","Recarga":"1.5h/15min=1h","ANC":"Sim (Advanced ANC II+)","Microfone":"6 mics","IPX":"IP57","Peso":"6.5g/fone","Codec":"SBC, AAC, aptX Lossless, LE Audio"},pros:["ANC aprimorado vs 1ª geração","aptX Lossless + LE Audio","IP57","6 mics — melhor qualidade de chamada do mercado","Multiponto 3 dispositivos"],cons:["Foco em produtividade","Sem LDAC","Preço elevado","Autonomia moderada (38h total)"],score:{"Som":87,"Conforto":84,"Autonomia":76,"Custo-Benefício":70,"Build":90},youtubeIds:["yBDHUW3L5Ec","rJPa5VCKW9s"],youtubeLabels:["Review","Call Quality"],amazon:"https://www.amazon.com.br/s?k=Jabra+Elite+10",ml:"https://lista.mercadolivre.com.br/jabra-elite-10",official:"https://www.jabra.com.br"},
{id:301,name:"Jabra Elite 10 (1ª geração)",brand:"Jabra",price:1499,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"6h+27h case","Recarga":"1.5h","ANC":"Sim (Advanced ANC II)","Microfone":"6 mics","IPX":"IP57","Peso":"6.0g/fone","Codec":"SBC, AAC, aptX Lossless"},pros:["aptX Lossless — qualidade CD","IP57","ANC Advanced II","6 mics chamadas líder","Multiponto 3 dispositivos"],cons:["Foco em produtividade mais que música","Sem LDAC","Autonomia curta (33h total)"],score:{"Som":86,"Conforto":84,"Autonomia":74,"Custo-Benefício":72,"Build":88},youtubeIds:["yBDHUW3L5Ec","rJPa5VCKW9s"],youtubeLabels:["Review","Call Quality"],amazon:"https://www.amazon.com.br/s?k=Jabra+Elite+10+gen+1",ml:"https://lista.mercadolivre.com.br/jabra-elite-10-gen1",official:"https://www.jabra.com.br"},
{id:302,name:"Jabra Elite 8 Active",brand:"Jabra",price:1299,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"8h+24h case","Recarga":"1.5h","ANC":"Sim (Adaptive ANC)","Microfone":"6 mics","IPX":"IP68","Peso":"6.5g/fone","Codec":"SBC, AAC, aptX Adaptive"},pros:["IP68 — imersão em água até 1m","ANC adaptativo","6 mics","aptX Adaptive","Ganchos seguros para esporte"],cons:["Sem LDAC","32h total","Design esportivo não é discreto","Preço elevado"],score:{"Som":84,"Conforto":80,"Autonomia":76,"Custo-Benefício":70,"Build":90},youtubeIds:["yBDHUW3L5Ec","rJPa5VCKW9s"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Jabra+Elite+8+Active",ml:"https://lista.mercadolivre.com.br/jabra-elite-8-active",official:"https://www.jabra.com.br"},
{id:303,name:"Jabra Elite 4",brand:"Jabra",price:499,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.2","Autonomia":"7h+21h case","Recarga":"1.5h","ANC":"Sim","Microfone":"4 mics","IPX":"IP55","Peso":"5.5g/fone","Codec":"SBC, AAC"},pros:["ANC eficiente escritório","IP55","Multiponto 2 dispositivos","Qualidade chamada Jabra","Entrada na linha Elite"],cons:["Sem LDAC","Driver 6mm","Foco em produtividade","28h total"],score:{"Som":76,"Conforto":80,"Autonomia":74,"Custo-Benefício":78,"Build":78},youtubeIds:["J0Xhv2Hb3bE","TCEKhR7-Jus"],youtubeLabels:["Review","Call Quality"],amazon:"https://www.amazon.com.br/s?k=Jabra+Elite+4",ml:"https://lista.mercadolivre.com.br/jabra-elite-4",official:"https://www.jabra.com.br"},
{id:304,name:"Jabra Evolve2 Buds",brand:"Jabra",price:1299,tier:"premium",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.2","Autonomia":"8h+24h case","Recarga":"1.5h","ANC":"Sim","Microfone":"6 mics","IPX":"IPX5","Peso":"6.5g/fone","Codec":"SBC, AAC"},pros:["Melhor microfone profissional","ANC eficaz escritório","6 mics por fone","IPX5","Multiponto 3 dispositivos","Certificado Teams/Zoom"],cons:["Foco em produtividade não música","Preço elevado","Sem LDAC","32h total"],score:{"Som":78,"Conforto":84,"Autonomia":78,"Custo-Benefício":68,"Build":84},youtubeIds:["9HO5EBNL5jY","OscAzMBxT7E"],youtubeLabels:["Review","Call Test"],amazon:"https://www.amazon.com.br/s?k=Jabra+Evolve2+Buds",ml:"https://lista.mercadolivre.com.br/jabra-evolve2-buds",official:"https://www.jabra.com.br"},
{id:305,name:"Jabra Evolve2 55",brand:"Jabra",price:1599,tier:"premium",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.2","Autonomia":"36h ANC","Recarga":"2h","ANC":"Sim (avançado)","Microfone":"10 mics+braço retrátil","Dobrável":"Sim","Peso":"222g","Codec":"SBC, AAC, aptX"},pros:["Melhor microfone do mercado com braço retrátil","ANC focado produtividade","3 dispositivos simultâneos","Ideal home office","Confortável 8h+","Certificado Teams/Zoom"],cons:["Som neutro não musical","Sem LDAC","Preço premium para chamadas"],score:{"Som":82,"Conforto":90,"Autonomia":85,"Custo-Benefício":72,"Build":86},youtubeIds:["FfQYMFIDa7Y","BIMZ8gVXuGo"],youtubeLabels:["Review","Mic Test"],amazon:"https://www.amazon.com.br/s?k=Jabra+Evolve2+55",ml:"https://lista.mercadolivre.com.br/jabra-evolve2-55",official:"https://www.jabra.com.br"},

// ── PHILIPS ───────────────────────────────────────────────────────────────────
{id:310,name:"Philips TAH8506",brand:"Philips",price:799,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"60h sem ANC/30h ANC","Recarga":"2h","ANC":"Sim (Pro+)","Microfone":"Sim","Dobrável":"Sim","Peso":"248g","Codec":"SBC, AAC, aptX"},pros:["60h sem ANC","ANC Pro+","aptX","App Philips Headphones","Design premium"],cons:["Sem LDAC","BT 5.0","App básico"],score:{"Som":82,"Conforto":80,"Autonomia":94,"Custo-Benefício":76,"Build":78},youtubeIds:["cQBKbp8ZBQI","mFQGkWDvVvI"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Philips+TAH8506",ml:"https://lista.mercadolivre.com.br/philips-tah8506",official:"https://www.philips.com.br"},
{id:311,name:"Philips TAH5205",brand:"Philips",price:399,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"29h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"197g","Codec":"SBC, AAC"},pros:["29h de autonomia","Leve 197g","Dobrável","Preço acessível","Design elegante"],cons:["Sem ANC","Sem LDAC","BT 5.0"],score:{"Som":70,"Conforto":76,"Autonomia":82,"Custo-Benefício":80,"Build":68},youtubeIds:["cQBKbp8ZBQI","mFQGkWDvVvI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philips+TAH5205",ml:"https://lista.mercadolivre.com.br/philips-tah5205",official:"https://www.philips.com.br"},
{id:312,name:"Philips TAH1205",brand:"Philips",price:129,tier:"budget",type:"Over-ear",specs:{"Driver":"32mm","Bluetooth":"5.0","Autonomia":"15h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"148g","Codec":"SBC, AAC"},pros:["Preço ~R$129","Carga 15min=3h","Leve e dobrável","Top vendas Amazon BR"],cons:["Sem ANC","Build plástico básico","Autonomia curta 15h"],score:{"Som":62,"Conforto":68,"Autonomia":70,"Custo-Benefício":86,"Build":55},youtubeIds:["cQBKbp8ZBQI","mFQGkWDvVvI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philips+TAH1205",ml:"https://lista.mercadolivre.com.br/philips-tah1205",official:"https://www.philips.com.br"},
{id:313,name:"Philips TAT3217",brand:"Philips",price:199,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.3","Autonomia":"6h+24h case","Recarga":"1h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"4g/fone","Codec":"SBC, AAC"},pros:["Leve 4g","30h total","IPX4","BT 5.3","Carga 15min=1h"],cons:["Sem ANC","Sem LDAC","Driver 6mm"],score:{"Som":64,"Conforto":72,"Autonomia":78,"Custo-Benefício":82,"Build":60},youtubeIds:["cQBKbp8ZBQI","mFQGkWDvVvI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philips+TAT3217",ml:"https://lista.mercadolivre.com.br/philips-tat3217",official:"https://www.philips.com.br"},
{id:314,name:"Philips TAT2000",brand:"Philips",price:149,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"6mm","Bluetooth":"5.3","Autonomia":"6h+22h case","Recarga":"1h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"3.8g/fone","Codec":"SBC, AAC"},pros:["3.8g — ultraleve","28h total","IPX4","BT 5.3","Design ear-clip open-fit"],cons:["Sem ANC","Sem LDAC","Autonomia básica"],score:{"Som":62,"Conforto":74,"Autonomia":74,"Custo-Benefício":80,"Build":58},youtubeIds:["t6kqGQ-wYT8","xP3OdKLW4LA"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Philips+TAT2000",ml:"https://lista.mercadolivre.com.br/philips-tat2000",official:"https://www.philips.com.br"},

// ── SHOKZ ─────────────────────────────────────────────────────────────────────
{id:320,name:"Shokz OpenRun Pro 2",brand:"Shokz",price:1999,tier:"premium",type:"Condução Óssea",specs:{"Driver":"Condução óssea 10ª geração + DualPitch","Bluetooth":"5.3","Autonomia":"12h","Recarga":"1h/5min=1.5h","ANC":"Não (open-ear)","Microfone":"2 mics com cVc","IPX":"IP55","Peso":"30g","Codec":"SBC, AAC"},pros:["Tecnologia DualPitch — graves 10% mais intensos","12h de autonomia — melhor da linha","Ultraleve 30g","Ideal para corrida/ciclismo","Segurança total — ouve ambiente"],cons:["Sem ANC por design","Graves fracos vs TWS","Preço elevado","Não para ambientes ruidosos"],score:{"Som":72,"Conforto":94,"Autonomia":84,"Custo-Benefício":68,"Build":88},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Running Test"],amazon:"https://www.amazon.com.br/s?k=Shokz+OpenRun+Pro+2",ml:"https://lista.mercadolivre.com.br/shokz-openrun-pro-2",official:"https://shokz.com"},
{id:321,name:"Shokz OpenRun Pro",brand:"Shokz",price:1649,tier:"premium",type:"Condução Óssea",specs:{"Driver":"Condução óssea 9ª geração TurboPitch","Bluetooth":"5.1","Autonomia":"10h","Recarga":"1h/5min=1.5h","ANC":"Não (open-ear)","Microfone":"2 mics","IPX":"IP55","Peso":"29g","Codec":"SBC, AAC"},pros:["Tecnologia TurboPitch — melhor som da linha anterior","10h autonomia","Ultraleve 29g","IP55","Ideal para atletas"],cons:["Sem ANC por design","Geração anterior ao Pro 2","Não para ambientes ruidosos"],score:{"Som":70,"Conforto":92,"Autonomia":82,"Custo-Benefício":72,"Build":86},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Sports Test"],amazon:"https://www.amazon.com.br/s?k=Shokz+OpenRun+Pro",ml:"https://lista.mercadolivre.com.br/shokz-openrun-pro",official:"https://shokz.com"},
{id:322,name:"Shokz OpenRun",brand:"Shokz",price:1499,tier:"premium",type:"Condução Óssea",specs:{"Driver":"Condução óssea 8ª geração PremiumPitch 2.0","Bluetooth":"5.1","Autonomia":"8h","Recarga":"1h/10min=1.5h","ANC":"Não (open-ear)","Microfone":"2 mics","IPX":"IP67","Peso":"26g","Codec":"SBC, AAC"},pros:["IP67 — mais resistente à água","Ultraleve 26g","Modelo mais vendido da Shokz","Carregamento magnético","Custo-benefício na linha"],cons:["Sem ANC por design","8h — menor que o Pro","Som menos potente que o Pro"],score:{"Som":66,"Conforto":92,"Autonomia":76,"Custo-Benefício":74,"Build":84},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","vs Pro"],amazon:"https://www.amazon.com.br/s?k=Shokz+OpenRun",ml:"https://lista.mercadolivre.com.br/shokz-openrun",official:"https://shokz.com"},
{id:323,name:"Shokz OpenFit Air",brand:"Shokz",price:1449,tier:"premium",type:"Open-ear",specs:{"Driver":"10mm open-ear DirectPitch","Bluetooth":"5.2","Autonomia":"7h+28h case","Recarga":"1.5h","ANC":"Não (open-ear)","Microfone":"2 mics","IPX":"IPX5","Peso":"8g/fone","Codec":"SBC, AAC"},pros:["Formato TWS open-ear — ouvido livre","8g por fone — ultracompacto","28h total com case","Confortável sem ponteira","Ideal para longas jornadas"],cons:["Sem ANC por design","Graves fracos open-ear","Preço elevado para TWS sem ANC"],score:{"Som":64,"Conforto":90,"Autonomia":80,"Custo-Benefício":68,"Build":80},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Shokz+OpenFit+Air",ml:"https://lista.mercadolivre.com.br/shokz-openfit-air",official:"https://shokz.com"},

// ── HAYLOU ────────────────────────────────────────────────────────────────────
// Over-ear
{id:330,name:"Haylou S35 ANC",brand:"HAYLOU",price:349,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.2","Autonomia":"60h sem ANC/40h ANC","Recarga":"2h","ANC":"Sim (-43dB)","Microfone":"Sim","Dobrável":"Sim","Peso":"240g","Codec":"SBC, AAC"},pros:["60h sem ANC por preço acessível","ANC -43dB funcional","Dobrável","Custo-benefício forte"],cons:["Sem LDAC","App básico","Build plástico","ANC intermediário"],score:{"Som":72,"Conforto":76,"Autonomia":95,"Custo-Benefício":84,"Build":64},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Haylou+S35+ANC",ml:"https://lista.mercadolivre.com.br/haylou-s35-anc",official:"https://www.haylou.com"},
{id:331,name:"Haylou S30 Pro",brand:"HAYLOU",price:266,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.4","Autonomia":"80h sem ANC/50h ANC","Recarga":"2h/10min=5h","ANC":"Sim (híbrido, -43dB)","Microfone":"Sim + boom removível","Dobrável":"Sim","Peso":"260g","Codec":"SBC, AAC"},pros:["80h sem ANC — recorde na faixa","Microfone boom removível — dual-use","BT 5.4","Carregamento rápido","ANC híbrido"],cons:["Sem LDAC","Build plástico básico","ANC intermediário","Microfone boom não é studio"],score:{"Som":70,"Conforto":76,"Autonomia":98,"Custo-Benefício":88,"Build":62},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Mic Test"],amazon:"https://www.amazon.com.br/s?k=Haylou+S30+Pro",ml:"https://lista.mercadolivre.com.br/haylou-s30-pro",official:"https://www.haylou.com"},
{id:332,name:"Haylou S30",brand:"HAYLOU",price:249,tier:"budget",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.2","Autonomia":"80h sem ANC/50h ANC","Recarga":"2h","ANC":"Sim (-43dB)","Microfone":"Sim","Dobrável":"Sim","Peso":"250g","Codec":"SBC, AAC"},pros:["80h sem ANC — excepcional para o preço","ANC funcional","Custo-benefício único","Dobrável"],cons:["Sem LDAC","Sem microfone boom (diferença do Pro)","Build plástico","ANC intermediário"],score:{"Som":68,"Conforto":74,"Autonomia":98,"Custo-Benefício":90,"Build":60},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Haylou+S30",ml:"https://lista.mercadolivre.com.br/haylou-s30",official:"https://www.haylou.com"},
// Condução óssea Haylou
{id:333,name:"Haylou PurFree BC01",brand:"HAYLOU",price:449,tier:"mid",type:"Condução Óssea",specs:{"Driver":"Condução óssea IP67","Bluetooth":"5.2","Autonomia":"8h","Recarga":"1h","ANC":"Não (open-ear)","Microfone":"2 mics cVc 8.0","IPX":"IP67","Peso":"28g","Codec":"SBC, AAC, aptX"},pros:["IP67 resistência à água","aptX","8h autonomia","28g ultraleve","Ideal para corrida com segurança"],cons:["Sem ANC por design","Graves fracos","Marca menos conhecida que Shokz"],score:{"Som":62,"Conforto":88,"Autonomia":78,"Custo-Benefício":80,"Build":76},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Running Test"],amazon:"https://www.amazon.com.br/s?k=Haylou+PurFree+BC01",ml:"https://lista.mercadolivre.com.br/haylou-purfree-bc01",official:"https://www.haylou.com"},
// TWS Haylou
{id:334,name:"Haylou W1",brand:"HAYLOU",price:399,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"7.2mm","Bluetooth":"5.2","Autonomia":"6h+24h case","Recarga":"1.5h","ANC":"Sim","Microfone":"4 mics cVc 8.0","IPX":"IPX4","Peso":"5g/fone","Codec":"SBC, AAC, aptX Adaptive"},pros:["aptX Adaptive por R$399","Chip Qualcomm","4 mics cVc 8.0","ANC funcional","Som de alta qualidade"],cons:["Sem LDAC","App básico","30h total","Build intermediário"],score:{"Som":80,"Conforto":76,"Autonomia":76,"Custo-Benefício":82,"Build":70},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Haylou+W1",ml:"https://lista.mercadolivre.com.br/haylou-w1",official:"https://www.haylou.com"},
{id:335,name:"Haylou GT7 Neo",brand:"HAYLOU",price:99,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.2","Autonomia":"6.5h+22h case","Recarga":"1h","ANC":"Não","Microfone":"ENC IA","IPX":"IPX4","Peso":"3.9g/fone","Codec":"SBC, AAC"},pros:["~R$99","3.9g — muito leve","ENC IA em chamadas","28.5h total","IPX4"],cons:["Sem ANC","Sem LDAC","Driver 8mm","App básico"],score:{"Som":62,"Conforto":72,"Autonomia":78,"Custo-Benefício":88,"Build":58},youtubeIds:["4oN3EbGnmB4","M_RJ7WPJLDI"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Haylou+GT7+Neo",ml:"https://lista.mercadolivre.com.br/haylou-gt7-neo",official:"https://www.haylou.com"},

// ── BASEUS ────────────────────────────────────────────────────────────────────
{id:340,name:"Baseus H1i Bowie",brand:"Baseus",price:269,tier:"budget",type:"Over-ear",specs:{"Driver":"10mm","Bluetooth":"5.2","Autonomia":"100h sem ANC","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"220g","Codec":"SBC, AAC"},pros:["100h sem ANC — recorde absoluto","ANC incluído","Leve 220g","Dobrável","Custo-benefício excelente"],cons:["Sem LDAC","ANC básico","App mínimo","Driver 10mm"],score:{"Som":68,"Conforto":74,"Autonomia":99,"Custo-Benefício":88,"Build":62},youtubeIds:["nJxHRNcG2QI","4vLpIv_gFao"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Baseus+H1i+Bowie",ml:"https://lista.mercadolivre.com.br/baseus-h1i-bowie",official:"https://www.baseus.com"},
{id:341,name:"Baseus Bowie MA10 Pro",brand:"Baseus",price:469,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"11mm+BA","Bluetooth":"5.3","Autonomia":"9h+32h case","Recarga":"1.5h","ANC":"Sim (4 mics)","Microfone":"4 mics","IPX":"IPX4","Peso":"5.8g/fone","Codec":"SBC, AAC, LDAC"},pros:["LDAC + driver híbrido","ANC 4 mics","41h total","Ajuste ergonômico"],cons:["App básico","Build intermediário","IPX4 apenas","Marca menos conhecida"],score:{"Som":78,"Conforto":76,"Autonomia":84,"Custo-Benefício":82,"Build":66},youtubeIds:["nJxHRNcG2QI","4vLpIv_gFao"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=Baseus+MA10+Pro",ml:"https://lista.mercadolivre.com.br/baseus-ma10-pro",official:"https://www.baseus.com"},
{id:342,name:"Baseus Bowie M2s",brand:"Baseus",price:149,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+28h case","Recarga":"1.5h","ANC":"Não","Microfone":"ENC","IPX":"IPX5","Peso":"4.5g/fone","Codec":"SBC, AAC"},pros:["Som neutro e equilibrado","IPX5","35h total","Leve 4.5g","Custo-benefício sólido"],cons:["Sem ANC","Sem LDAC","App inexistente","Marca pouco conhecida"],score:{"Som":66,"Conforto":74,"Autonomia":80,"Custo-Benefício":86,"Build":60},youtubeIds:["nJxHRNcG2QI","4vLpIv_gFao"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Baseus+Bowie+M2s",ml:"https://lista.mercadolivre.com.br/baseus-bowie-m2s",official:"https://www.baseus.com"},
{id:343,name:"Baseus Bowie EZ10",brand:"Baseus",price:79,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"6h+24h case","Recarga":"1.5h","ANC":"Não","Microfone":"ENC","IPX":"IPX5","Peso":"3.8g/fone","Codec":"SBC, AAC"},pros:["~R$79 — muito barato","IPX5","30h total","3.8g ultraleve","BT 5.3"],cons:["Sem ANC","Sem LDAC","Qualidade sonora básica","App inexistente"],score:{"Som":58,"Conforto":68,"Autonomia":74,"Custo-Benefício":88,"Build":54},youtubeIds:["nJxHRNcG2QI","4vLpIv_gFao"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Baseus+EZ10",ml:"https://lista.mercadolivre.com.br/baseus-ez10",official:"https://www.baseus.com"},

// ── LENOVO ────────────────────────────────────────────────────────────────────
{id:350,name:"Lenovo LP7",brand:"Lenovo",price:119,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.0","Autonomia":"5h+25h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"5g/fone","Codec":"SBC, AAC"},pros:["Preço baixo","IPX4","30h total","Design clássico","Marca conhecida"],cons:["Sem ANC","Sem LDAC","BT 5.0","Qualidade básica"],score:{"Som":58,"Conforto":66,"Autonomia":74,"Custo-Benefício":84,"Build":54},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Lenovo+LP7",ml:"https://lista.mercadolivre.com.br/lenovo-lp7",official:"https://www.lenovo.com/br"},
{id:351,name:"Lenovo XT88",brand:"Lenovo",price:159,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"10mm","Bluetooth":"5.3","Autonomia":"7h+28h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX5","Peso":"5.1g/fone","Codec":"SBC, AAC"},pros:["IPX5","35h total","BT 5.3","Som equilibrado para o preço","Design compacto"],cons:["Sem ANC","Sem LDAC","App inexistente","Qualidade intermediária"],score:{"Som":62,"Conforto":70,"Autonomia":80,"Custo-Benefício":82,"Build":58},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Lenovo+XT88",ml:"https://lista.mercadolivre.com.br/lenovo-xt88",official:"https://www.lenovo.com/br"},
{id:352,name:"Lenovo XT96",brand:"Lenovo",price:199,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"13mm","Bluetooth":"5.1","Autonomia":"7h+28h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX5","Peso":"5.5g/fone","Codec":"SBC, AAC"},pros:["Driver 13mm — maior da linha","IPX5","35h total","Som com graves marcantes","Design gamer"],cons:["Sem ANC","Sem LDAC","BT 5.1","App inexistente"],score:{"Som":64,"Conforto":68,"Autonomia":80,"Custo-Benefício":80,"Build":60},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=Lenovo+XT96",ml:"https://lista.mercadolivre.com.br/lenovo-xt96",official:"https://www.lenovo.com/br"},
{id:353,name:"Lenovo GM2 Pro",brand:"Lenovo",price:79,tier:"budget",type:"In-ear (TWS)",specs:{"Driver":"13mm","Bluetooth":"5.3","Autonomia":"4h+16h case","Recarga":"1.5h","ANC":"Não","Microfone":"Sim","IPX":"IPX4","Peso":"3.8g/fone","Codec":"SBC, AAC"},pros:["~R$79 — muito barato","Modo gamer 60ms latência","BT 5.3","3.8g ultraleve","Design gamer atraente"],cons:["Sem ANC","20h total — curto","Sem LDAC","Qualidade sonora básica"],score:{"Som":58,"Conforto":66,"Autonomia":64,"Custo-Benefício":86,"Build":56},youtubeIds:["RLSO5RxIjkk","hd0xlhHJGh4"],youtubeLabels:["Review","Gaming Test"],amazon:"https://www.amazon.com.br/s?k=Lenovo+GM2+Pro",ml:"https://lista.mercadolivre.com.br/lenovo-gm2-pro",official:"https://www.lenovo.com/br"},

// ── BANG & OLUFSEN ────────────────────────────────────────────────────────────
{id:360,name:"Bang & Olufsen Beoplay H95",brand:"Bang & Olufsen",price:4999,tier:"flagship",type:"Over-ear",specs:{"Driver":"40mm titânio dual","Bluetooth":"5.1","Autonomia":"38h ANC/50h sem ANC","Recarga":"2h","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","Dobrável":"Sim","Peso":"323g","Codec":"SBC, AAC, aptX"},pros:["Materiais de luxo — titânio + couro cordeiro + espuma memória","ANC adaptativo excepcional","50h sem ANC","Case em alumínio inclusa","Adaptador de avião incluso","Design icônico"],cons:["Preço altíssimo ~R$4.999","Sem LDAC","BT 5.1 — antigo para o preço","Pesado 323g"],score:{"Som":92,"Conforto":96,"Autonomia":88,"Custo-Benefício":42,"Build":99},youtubeIds:["fS_0xtHxoGc","Yl_YEHX6JpY"],youtubeLabels:["Review","vs Sony XM5"],amazon:"https://www.amazon.com.br/s?k=Bang+Olufsen+Beoplay+H95",ml:"https://lista.mercadolivre.com.br/bang-olufsen-beoplay-h95",official:"https://www.bang-olufsen.com"},
{id:361,name:"Bang & Olufsen Beoplay EX",brand:"Bang & Olufsen",price:3499,tier:"flagship",type:"In-ear (TWS)",specs:{"Driver":"9.2mm titânio","Bluetooth":"5.2","Autonomia":"6h+14h case","Recarga":"1h (wireless)","ANC":"Sim (Adaptive ANC)","Microfone":"4 mics","IPX":"IP57","Peso":"5.7g/fone","Codec":"SBC, AAC, aptX Adaptive"},pros:["Design em alumínio e titânio — luxo","aptX Adaptive","IP57","ANC adaptativo de alto nível","Wireless charging","Design icônico"],cons:["Preço muito elevado","20h total — curto para o preço","Sem LDAC","Marca nichada no BR"],score:{"Som":90,"Conforto":86,"Autonomia":66,"Custo-Benefício":40,"Build":98},youtubeIds:["eIFE-8F5Mtg","UZi1ZzWYibs"],youtubeLabels:["Review","Design Tour"],amazon:"https://www.amazon.com.br/s?k=Bang+Olufsen+Beoplay+EX",ml:"https://lista.mercadolivre.com.br/bang-olufsen-beoplay-ex",official:"https://www.bang-olufsen.com"},
{id:362,name:"Bang & Olufsen Beoplay Portal",brand:"Bang & Olufsen",price:3999,tier:"flagship",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.1","Autonomia":"12h ANC PC/19h ANC mobile","Recarga":"3h","ANC":"Sim (3 modos)","Microfone":"8 mics","Dobrável":"Não","Peso":"339g","Codec":"SBC, AAC, aptX Adaptive"},pros:["Projetado para gaming","8 mics — qualidade de comunicação","aptX Adaptive","3 modos ANC","Design premium"],cons:["Autonomia baixa (12h no modo PC)","Sem LDAC","Pesado 339g","Nichado para gaming — menos versátil"],score:{"Som":88,"Conforto":86,"Autonomia":60,"Custo-Benefício":38,"Build":96},youtubeIds:["fS_0xtHxoGc","Yl_YEHX6JpY"],youtubeLabels:["Review","Gaming Test"],amazon:"https://www.amazon.com.br/s?k=Bang+Olufsen+Beoplay+Portal",ml:"https://lista.mercadolivre.com.br/bang-olufsen-beoplay-portal",official:"https://www.bang-olufsen.com"},

// ── AKG ───────────────────────────────────────────────────────────────────────
{id:370,name:"AKG N700NC M2",brand:"AKG",price:999,tier:"premium",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"25h ANC/30h sem ANC","Recarga":"2h","ANC":"Sim (Adaptativo)","Microfone":"4 mics","Dobrável":"Sim","Peso":"272g","Codec":"SBC, AAC, aptX, aptX LL"},pros:["ANC adaptativo eficaz","aptX LL para vídeo","Design premium dobrável","Uso com fio possível (sem bateria)","Qualidade Samsung/AKG"],cons:["Sem LDAC","30h abaixo dos concorrentes","Marca menos visível no BR"],score:{"Som":86,"Conforto":84,"Autonomia":76,"Custo-Benefício":74,"Build":82},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=AKG+N700NC+M2",ml:"https://lista.mercadolivre.com.br/akg-n700nc-m2",official:"https://www.akg.com"},
{id:371,name:"AKG Y600NC Wireless",brand:"AKG",price:699,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"5.0","Autonomia":"36h sem ANC/16h ANC","Recarga":"2h","ANC":"Sim","Microfone":"Sim","Dobrável":"Sim","Peso":"228g","Codec":"SBC, AAC, aptX"},pros:["36h sem ANC","ANC incluído","aptX","Leve 228g","Dobrável"],cons:["Sem LDAC","ANC 16h — limitado","BT 5.0"],score:{"Som":78,"Conforto":80,"Autonomia":82,"Custo-Benefício":74,"Build":72},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=AKG+Y600NC",ml:"https://lista.mercadolivre.com.br/akg-y600nc",official:"https://www.akg.com"},
{id:372,name:"AKG Y500 Wireless",brand:"AKG",price:499,tier:"mid",type:"Over-ear",specs:{"Driver":"40mm","Bluetooth":"4.2","Autonomia":"33h","Recarga":"2h","ANC":"Não","Microfone":"Sim","Dobrável":"Sim","Peso":"208g","Codec":"SBC, AAC, aptX"},pros:["33h de autonomia","aptX","Leve 208g","Dobrável","Design colorido atraente"],cons:["Sem ANC","BT 4.2 — desatualizado","Sem LDAC"],score:{"Som":74,"Conforto":78,"Autonomia":84,"Custo-Benefício":74,"Build":70},youtubeIds:["cFAFdq2kf1c","x7dX3KJvqNk"],youtubeLabels:["Review","Unboxing"],amazon:"https://www.amazon.com.br/s?k=AKG+Y500+Wireless",ml:"https://lista.mercadolivre.com.br/akg-y500-wireless",official:"https://www.akg.com"},
{id:373,name:"AKG N400NC TWS",brand:"AKG",price:599,tier:"mid",type:"In-ear (TWS)",specs:{"Driver":"8mm","Bluetooth":"5.0","Autonomia":"5h+20h case","Recarga":"1h","ANC":"Sim","Microfone":"3 mics","IPX":"IPX5","Peso":"7g/fone","Codec":"SBC, AAC, aptX"},pros:["ANC eficiente","aptX","IPX5","Qualidade Samsung/AKG","Design minimalista"],cons:["25h total — curto","BT 5.0","Sem LDAC","Driver 8mm"],score:{"Som":78,"Conforto":76,"Autonomia":68,"Custo-Benefício":72,"Build":76},youtubeIds:["VXXJ67TsDuQ","mj9zTGhzF10"],youtubeLabels:["Review","ANC Test"],amazon:"https://www.amazon.com.br/s?k=AKG+N400NC",ml:"https://lista.mercadolivre.com.br/akg-n400nc",official:"https://www.akg.com"},
